name: Ejecucion de un pipeline basico
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
env:
  env_var: ${{ vars.TEST_VAR }}
 
jobs:
  display-variables:
    name: env_var
    runs-on: ubuntu-latest
    steps:
      - name: Ejecucion de pruebas de clidad
        run:
          echo "“Ejecución de pruebas de SAST"
      - uses: actions/checkout@master
      - name: creacion de archivo de credenciales
        uses: mshick/fast-envsubst@v1
        #uses: actions/envsubst@v1
        env:
           USERNAME: ${{ secrets.USERNAME  }}
           PASSWORD: ${{ secrets.PASSWORD  }}
        with:
          input: ./credentials.ini.tpl
          output: ./credentials.ini
        #run:  envsubst < credentials.ini.tpl > credentials.ini
          #cp ./credentials.ini.tpl credentials.ini &&
          #sed -i 's/username/${{ secrets.USERNAME }}/g' credentials.ini
          
          
       
#jobs:
 # runs-on: ubuntu-latest
