name: Ejecucion de un pipeline basico
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
env:
  env_var: ${{ vars.TEST_VAR }}
 
jobs:
  display-variables:
    name: ${env_var}
    runs-on: ubuntu-latest
    steps:
      - name: Ejecucion de pruebas de clidad
        run:
          echo "Ejecución de pruebas de SAST"
      - uses: actions/checkout@master
      - name: creacion de archivo de credenciales
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: create file
        run : |
          sed -e "s/\${USERNAME}/${USERNAME}/g" -e "s/\${PASSWORD}/${PASSWORD}/g" credentials.ini.tpl > credentials.ini
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: commit changues
        run: |
          git config --local user.email "a.cmejia10@gmail.com"
          git config --local user.name "alexcst90"
          git add credentials.ini
          git commit -m "Update credentials.ini"
          git push

      - name: Build docker image
        run: |
          docker build -t devops_ws . --tag devops_ws_:$(date +%s)
          
        #run:  envsubst < credentials.ini.tpl > credentials.ini
          #cp ./credentials.ini.tpl credentials.ini &&
          #sed -i 's/username/${{ secrets.USERNAME }}/g' credentials.ini
          
          
       
#jobs:
 # runs-on: ubuntu-latest
