name: Ejecucion de un pipeline basico
on:
  workflow_dispatch:
env:
  env_var: ${{ secret.USERNAME }}

jobs:
  display-variables:
    name: ${{ secret.USERNAME }}
    runs-on: ubuntu-latest

#jobs:
 # runs-on: ubuntu-latest
