name: Ejecucion de un pipeline basico
on:
  workflow_dispatch:
env:
  env_var: $TEST_VAR

jobs:
  display-variables:
    name: ${{ env.TEST_VAR }}
    runs-on: ubuntu-latest
    steps:
      - name: Is productive branch
        run:
          echo "branch"+env_var
#jobs:
 # runs-on: ubuntu-latest
